default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: logistics_db_pass
  host: logistics_db
  pool: 5

marketplace: &marketplace
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: marketplace_db_pass
  host: marketplace_db
  pool: 5

development:
  logistics_db:
    <<: *default
    database: ofb_development
  logistics_db_replica:
    <<: *default
    database: ofb_development
    replica: true
  marketplace_db:
    <<: *marketplace
    database: epelia_development
  marketplace_db_replica:
    <<: *marketplace
    database: epelia_development
    replica: true

test:
  logistics_db:
    <<: *default
    database: ofb_test
  logistics_db_replica:
    <<: *default
    database: ofb_test
    replica: true
  marketplace_db:
    <<: *marketplace
    database: epelia_test
  marketplace_db_replica:
    <<: *marketplace
    database: epelia_test
    replica: true



production:
  logistics_db:
    <<: *default
    database: ofb_production
  logistics_db_replica:
    <<: *default
    database: ofb_production
    replica: true
  marketplace_db:
    <<: *marketplace
    database: epelia_production
  marketplace_db_replica:
    <<: *marketplace
    database: epelia_production
    replica: true

