# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: logistics_db
  username: postgres
  password: logistics_db_pass
  pool: 5

development:
  <<: *default
  database: ofb_development

test:
  <<: *default
  database: ofb_test

production:
  <<: *default
  database: ofb_production
